//LOADER ACTION TYPES
export const START_LOADER = 'START_LOADER';
export const STOP_LOADER = 'STOP_LOADER';

// CRYPTO ACTION TYPES
export const SET_PHRASE_ENTROPY = 'SET_PHRASE_ENTROPY';
export const GET_PHRASE_ENTROPY = 'GET_PHRASE_ENTROPY';

export const GENERATE_PHRASE_REQUEST = 'GENERATE_PHRASE_REQUEST';
export const GENERATE_PHRASE_SUCCESS = 'GENERATE_PHRASE_SUCCESS';
export const GENERATE_PHRASE_FAILED = 'GENERATE_PHRASE_FAILED';

export const VALDIATE_PHRASE_REQUEST = 'VALDIATE_PHRASE_REQUEST';
export const VALDIATE_PHRASE_SUCCESS = 'VALDIATE_PHRASE_SUCCESS';
export const VALDIATE_PHRASE_FAILED = 'VALDIATE_PHRASE_FAILED';

export const GENERATE_WALLET_ADDRESS_REQUEST =
  'GENERATE_WALLET_ADDRESS_REQUEST';
export const GENERATE_WALLET_ADDRESS_SUCCESS =
  'GENERATE_WALLET_ADDRESS_SUCCESS';
export const GENERATE_WALLET_ADDRESS_FAILED = 'GENERATE_WALLET_ADDRESS_FAILED';

export const SET_PRIVATE_KEY = 'SET_PRIVATE_KEY';

export const SET_DEFAULT_WALLET = 'SET_DEFAULT_WALLET';

export const SET_DEFAULT_CURRENCY = 'SET_DEFAULT_CURRENCY';

export const RENAME_WALLET = 'RENAME_WALLET';
export const DELETE_WALLET = 'DELETE_WALLET';

export const SET_TOTAL_WALLET_BALANCE = 'SET_TOTAL_WALLET_BALANCE';

export const LOAD_WALLET_REQUEST = 'LOAD_WALLET_REQUEST';
export const LOAD_WALLET_SUCCESS = 'LOAD_WALLET_SUCCESS';
export const LOAD_WALLET_FAILED = 'LOAD_WALLET_FAILED';

export const UPDATE_TOKEN_LIST = 'UPDATE_TOKEN_LIST';

export const ADD_ERC_TOKEN_REQUEST = 'ADD_ERC_TOKEN_REQUEST';
export const ADD_ERC_TOKEN_SUCCESS = 'ADD_ERC_TOKEN_SUCCESS';
export const ADD_ERC_TOKEN_FAILED = 'ADD_ERC_TOKEN_FAILED';

export const UPDATE_ERC_TOKEN_REQUEST = 'UPDATE_ERC_TOKEN_REQUEST';
export const UPDATE_ERC_TOKEN_SUCCESS = 'UPDATE_ERC_TOKEN_SUCCESS';
export const UPDATE_ERC_TOKEN_FAILED = 'UPDATE_ERC_TOKEN_FAILED';

export const UPDATE_ERC_TOKEN_BALANCE = 'UPDATE_ERC_TOKEN_BALANCE';

export const GET_ALL_COIN_DETAILS_REQUEST = 'GET_ALL_COIN_DETAILS_REQUEST';
export const GET_ALL_COIN_DETAILS_SUCCESS = 'GET_ALL_COIN_DETAILS_SUCCESS';
export const GET_ALL_COIN_DETAILS_FAILED = 'GET_ALL_COIN_DETAILS_FAILED';

export const GET_COIN_DETAILS_REQUEST = 'GET_COIN_DETAILS_REQUEST';
export const GET_COIN_DETAILS_SUCCESS = 'GET_COIN_DETAILS_SUCCESS';
export const GET_COIN_DETAILS_FAILED = 'GET_COIN_DETAILS_FAILED';

export const GET_CURRENCY_COVERSION_REQUEST = 'GET_CURRENCY_COVERSION_REQUEST';
export const GET_CURRENCY_COVERSION_SUCCESS = 'GET_CURRENCY_COVERSION_SUCCESS';
export const GET_CURRENCY_COVERSION_FAILED = 'GET_CURRENCY_COVERSION_FAILED';

export const GET_CRYPTO_PRICE_REQUEST = 'GET_CRYPTO_PRICE_REQUEST';
export const GET_CRYPTO_PRICE_SUCCESS = 'GET_CRYPTO_PRICE_SUCCESS';
export const GET_CRYPTO_PRICE_FAILED = 'GET_CRYPTO_PRICE_FAILED';

// PROFILE ACTION TYPES
export const SET_TERMS_ACCEPTANCE = 'SET_TERMS_ACCEPTANCE';
export const SET_PRIVACY_PREFERENCES = 'SET_PRIVACY_PREFERENCES';
export const GET_PRIVACY_PREFERENCES = 'GET_PRIVACY_PREFERENCES';
export const SET_WALLET_BACKUP = 'SET_WALLET_BACKUP';

// USER PROFILE TYPES
export const SET_GOOGLE_USER = 'SET_GOOGLE_USER';
export const SET_WALLET_PROTECTION = 'SET_WALLET_PROTECTION';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

//POLICY ACTION TYPES
export const TERMS_SUCCESS = 'TERMS_SUCCESS';
export const TERMS_ERROR = 'TERMS_ERROR';
export const PRIVACY_POLICY_SUCCESS = 'PRIVACY_POLICY_SUCCESS';
export const PRIVACY_POLICY_ERROR = 'PRIVACY_POLICY_ERROR';

// AVAILABILITY TYPES
export const VALID_USERNAME_SUCCESS = 'VALID_USERNAME_SUCCESS';
export const VALID_USERNAME_ERROR = 'VALID_USERNAME_ERROR';
export const RESET_USERNAME_DATA = 'RESET_USERNAME_DATA';
export const SET_USERNAME = 'SET_USERNAME';

// LOGIN TYPES
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';

// LOGIN TYPES
export const NETWORK_LIST_SUCCESS = 'NETWORK_LIST_SUCCESS';
export const NETWORK_LIST_FAILED = 'NETWORK_LIST_FAILED';
export const UPDATE_NETWORK_LIST = 'UPDATE_NETWORK_LIST';
export const SET_ACTIVE_NETWORK = 'SET_ACTIVE_NETWORK';

// USER
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_USER_DETAILS_FAILED = 'UPDATE_USER_DETAILS_FAILED';
export const VALIDATION_SUCCESS = 'VALIDATION_SUCCESS';
export const VALIDATION_FAILED = 'VALIDATION_FAILED';

// APP LOCK
export const SET_APP_LOCK_PREFERENCES = 'SET_APP_LOCK_PREFERENCES';

// CURRENCY TYPES
export const CURRENCIES_LIST_SUCCESS = 'CURRENCIES_LIST_SUCCESS';
export const CURRENCIES_LIST_FAIL = 'CURRENCIES_LIST_FAIL';
export const CURRENCIES_DETAIL_SUCCESS = 'CURRENCIES_DETAIL_SUCCESS';
export const CURRENCIES_DETAIL_FAIL = 'CURRENCIES_DETAIL_FAIL';

export const GET_MARKET_DATA_SUCCESS = 'GET_MARKET_DATA_SUCCESS';

export const GET_TRANSACTION_HISTORY_REQUEST =
  'GET_TRANSACTION_HISTORY_REQUEST';
export const GET_TRANSACTION_HISTORY_SUCCESS =
  'GET_TRANSACTION_HISTORY_SUCCESS';
export const GET_TRANSACTION_HISTORY_FAILED = 'GET_TRANSACTION_HISTORY_FAILED';

// SWAP
export const SET_SWAP_SLIPPAGE = 'SET_SWAP_SLIPPAGE';
export const SET_SWAP_SPEED = 'SET_SWAP_SPEED';
export const SET_SWAP_TXN_TIME = 'SET_SWAP_TXN_TIME';

export const SWAP_REQUEST = 'SWAP_REQUEST';
export const SWAP_SUCCESS = 'SWAP_SUCCESS';
export const SWAP_FAILED = 'SWAP_FAILED';

export const SOCKET_COIN_DETAILS = 'Socket/COIN_DETAILS';
export const SOCKET_MARKET_DATA = 'Socket/MARKET_DATA';
