type RootStackParamList = {
  Loading: undefined;
  Onboarding: undefined;
  PrivacyPolicy: undefined;
  CreatePassword: undefined;
  CreatePasswordForm: undefined;
  SignInWithRecoveryPhrase: { phraseType?: '12' | '24' } | undefined;
  EmailVerification: undefined;
  EnterVerificationCode: undefined;
  Biometrics: { nextRoute?: string };
  ProtectWallet: undefined;
  BackupWallet: undefined;
  RestoreWallet: undefined;
  RecoveryPhraseWords: { phraseType?: '12' | '24' } | undefined;
  ManualBackup: undefined;
  ManualBackupFields: undefined;
  ManualBackupSuccess: { phraseType?: '12' | '24' } | undefined;
  ImportWallet: undefined;
  ImportAccount: undefined;
  EnterPassword: undefined;
  Home: undefined;
  WalletDetails: { token: any };
  Settings: undefined;
  Legal: { from?: string } | undefined;
  AppLock: undefined;
  AdvancedSettings: undefined;
  LocalCurrency: undefined;
  About: undefined;
  CreatePin: { alreadyAccount?: boolean };
  ConfirmPin: { newPin: string; alreadyAccount?: boolean };
  QRScanner: undefined;
  ReceiveETH: undefined;
  SecretRecoveryPhrase: undefined;
  Receive: undefined;
  RequestPayment: undefined;
  SendLink: { token: any; amount?: string };
  Send: { scannedAddress?: string } | undefined;
  Transactions: { token?: any; address?: string };
  TermsAndCondition: undefined;
  SendToken: {
    token: any;
    amount?: string;
    scannedAddress?: string;
    address?: string;
  };
  ReceiveVIP: { token: any; address?: string };
  ReceiveQr: { token: any; address?: string };
  Swap: undefined;
  PurchaseToken: undefined;
  Wallets: undefined;
  DeleteWallet: undefined;
  NotificationSettings: undefined;
  Notification: undefined;
  QrTicket: undefined;
  TermsOfService: undefined;
  ShowQR: { token: any; amount?: string };
  BlockExplorer: { url: string };
  ContactUs: undefined;
  ShowRecoveryPhrase: { phraseType?: '12' | '24' };
};
